[project]
name = "template-data"
version = "0.1.0"
description = "A template for data harvesting, processing, and serving solutions"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

